export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <h1 
          style={{
            color: 'blue',
            fontSize: '50px',
            textAlign: 'center',
          
          }}
          >Welcome to Next.js!</h1>

        </header>
        {children}
        
        <footer
        style={{
          backgroundColor: 'black',
          color: 'white',
          textAlign: 'center',
          padding: '10px',
          position: 'fixed',
          left: '0',
          bottom: '0',
          width: '100%',
        
        }}
        >
          <p>© 2024 Joy</p>

        </footer>
        </body>
        
    </html>
  )
}
